name: LunchLine
version: 0.1.0.0
github: 'bryanwtan/LunchLine'
license: BSD3
author: 'bryan'
maintainer: 'twotale.industries@gmail.com'
copyright: 'MIT-0'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/bryanwtan/LunchLine#readme>

dependencies:
  - base >= 4.7 && < 5
  - persistent
  - persistent-sqlite
  - mtl
  - resource-pool
  - monad-logger

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - DerivingStrategies
  - GeneralizedNewtypeDeriving

executables:
  LunchLine-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - LunchLine

tests:
  LunchLine-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - LunchLine
